# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    filePath: 'compile.sh'

- task: CopyFiles@2
  inputs:
    SourceFolder:
    Contents: 'lnCompile.bat'
    TargetFolder: 'Deply'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Deply'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: 'Deply'
    Contents: '**'
    ArtifactName: 'Test_repo1'
    ArtifactType: 'Container'
    
- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
