# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Initiated Build process!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    filePath: 'compile.sh'

- task: CopyPublishBuildArtifacts@1
  inputs:
    Contents: 'binary.tar.gz'
    ArtifactName: 'binary'
    ArtifactType: 'Container'

    
- script: 
    
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
